services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: myproject_db
      POSTGRES_USER: project_user
      POSTGRES_PASSWORD: test12345
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U project_user -d myproject_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: